[Paths]
; Абсолютный путь к папке ядра (сетевой или локальный)
; Пример сетевого диска: J:\Soft\autoprint\core\
; Изменяется через GUI без перекомпиляции print.exe
; Хранится локально в каждой копии папки !_Печать\config\config.ini
CorePath = J:\Soft\autoprint\core\